basic ml project v1

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -120,14 +120,27 @@ jobs:
             --associate-public-ip-address \
             --query 'Instances[0].InstanceId' \
             --output text)
-
-          echo "New EC2 instance created with ID: $INSTANCE_ID"
+          echo "Created EC2 instance with ID: $INSTANCE_ID"
           echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+
+      - name: Check if EC2 instance was created successfully
+        run: |
+          if [ "$INSTANCE_ID" == "None" ]; then
+            echo "EC2 instance creation failed!"
+            exit 1
+          else
+            echo "EC2 instance created with ID: $INSTANCE_ID"
+          fi
+
 
       - name: Wait for EC2 instance to be running
         run: |
-          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
-          echo "EC2 instance is now running."
+          if [ "$INSTANCE_ID" != "None" ]; then
+            aws ec2 wait instance-running --instance-ids $INSTANCE_ID
+            echo "EC2 instance is now running."
+          else
+            echo "Skipping EC2 wait because instance creation failed."
+          fi
 
       - name: Retrieve EC2 Public IP
         id: ec2-ip
